// GENERATED by tools/gen_constants.py from anonymizer/detector_patterns.py — do not edit by hand; regenerate.
package dev.filtsiap.ded.anonymizer;

import dev.filtsiap.ded.anonymizer.pycompat.PyRegex;
import dev.filtsiap.ded.anonymizer.pycompat.PyRegex.PyPattern;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** Regex and data constants for the deterministic detectors (port of {@code detector_patterns.py}). */
final class DetectorPatterns {

    /** Apostrophe variants used for the Greek elision in "υπ' αριθ." and FEK series letters. */
    static final String ELISION_APOSTROPHES = "\u2019'ʼ\u1fbd\u0384";

    /** Built-in pattern specs by name; {@code config/regex_patterns.yaml} overrides per key. Insertion-ordered. */
    static final Map<String, Map<String, String>> DEFAULT_PATTERNS;

    static {
        Map<String, Map<String, String>> patterns = new LinkedHashMap<>();
        patterns.put("afm", orderedSpec("prefix", "(?:Α\\.?Φ\\.?Μ\\.?|AFM)\\s*[:.]?\\s*", "body", "(\\d{9})"));
        patterns.put("amka", orderedSpec("prefix", "(?:ΑΜΚΑ|AMKA)\\s*[:.]?\\s*", "body", "(\\d{11})"));
        patterns.put("email", orderedSpec("body", "[\\w.+-]+@[\\w-]+\\.[\\w.-]+"));
        patterns.put("iban", orderedSpec("body", "[A-Z]{2}\\d{2}(?:[\\s-]?[A-Z0-9]){1,30}"));
        patterns.put("phone_intl", orderedSpec("body", "\\+30[\\s-]?(?:\\d[\\s-]?){10}"));
        patterns.put("phone_local", orderedSpec("body", "(?:2|6)\\d{9}"));
        patterns.put("phone_00", orderedSpec("body", "0030\\d{10}"));
        patterns.put("protocol_number", orderedSpec("prefix", "(?:αριθμ[οό]\\s+πρωτοκόλλου|αριθ\\.?\\s*πρωτ\\.?|αρ\\.?\\s*πρωτ\\.?|Πρωτ\\.?)\\s*[:.]?\\s*", "body", "([A-Za-z0-9Α-Ωα-ωΆ-ώ/\\-]*\\d[A-Za-z0-9Α-Ωα-ωΆ-ώ/\\-]*(?:/\\d{2,4})?)"));
        patterns.put("act_number", orderedSpec("body", "Πράξη\\s+([A-Za-z0-9Α-Ωα-ωΆ-ώ/\\-]*\\d[A-Za-z0-9Α-Ωα-ωΆ-ώ/\\-]*)"));
        patterns.put("audit_order", orderedSpec("prefix", "(?:εντολ[ήέ]ς?\\s+(?:μερικού\\s+)?ελέγχου|Γνωστοποίησ(?:η|εις)|Αίτημ(?:α|ατα)\\s+Παροχής\\s+Πληροφοριών|Πρόσκλησ(?:η|εις)|Πληροφοριακή\\s+Έκθεση|ΑΒΜ|ΕΞ)\\s+", "body", "([0-9]{2,}(?:\\s*[/&]\\s*[0-9]+)*(?:[/\\-]\\d{2,4}(?:[/\\-.]\\d{2,4})*)?)"));
        patterns.put("invoice_number", orderedSpec("body", "(?:Τιμολόγιο|Α/Α)\\s+(\\d+)"));
        patterns.put("transaction_id", orderedSpec("body", "(?:Συναλλαγή|ID)\\s*[:.]?\\s*([A-Za-z0-9]{6,})"));
        patterns.put("date_numeric", orderedSpec("body", "\\b(\\d{1,2})[/\\-.](\\d{1,2})[/\\-.](\\d{4})\\b"));
        patterns.put("date_greek", orderedSpec("body", "\\b(\\d{1,2})η?\\s+(Ιανουαρίου|Φεβρουαρίου|Μαρτίου|Απριλίου|Μαΐου|Ιουνίου|Ιουλίου|Αυγούστου|Σεπτεμβρίου|Οκτωβρίου|Νοεμβρίου|Δεκεμβρίου)\\s+(\\d{4})\\b"));
        patterns.put("dou", orderedSpec("body", "(?:Δ\\.Ο\\.Υ\\.|ΔΟΥ)\\s+([Α-ΩΆΈΉΊΌΎΏΪΫ][\\wΆ-ώ\\s]*)"));
        patterns.put("legal_ref_law", orderedSpec("body", "[Νν]\\.?\\s*(\\d+/\\d+)|νόμος\\s+(\\d+/\\d+)"));
        patterns.put("legal_ref_pd", orderedSpec("body", "Π\\.Δ\\.\\s*(\\d+/\\d+)"));
        patterns.put("legal_ref_short", orderedSpec("body", "(?:Κ\\.Φ\\.Δ\\.|Κ\\.Ν\\.)"));
        patterns.put("article_ref", orderedSpec("body", "(?:άρθρο|άρ\\.)\\s+\\d+(?:\\s*(?:παρ\\.|παράγραφος)\\s*\\d+)?|(?:παρ\\.|παράγραφος)\\s+\\d+|(?:εδάφιο|περ\\.)\\s+[α-ωΑ-Ω]"));
        patterns.put("court_decision", orderedSpec("body", "[ΑΑ]\\.\\d+/\\d{4}"));
        patterns.put("money", orderedSpec("body", "(?:€\\s*[\\d.,]+|[\\d.,]+\\s*(?:€|ευρώ))"));
        patterns.put("tax_year", orderedSpec("body", "(?:οικονομικό|φορολογικό)\\s+έτος\\s+\\d{4}|χρήση\\s+\\d{4}"));
        patterns.put("legal_ref_fek", orderedSpec("body", "ΦΕΚ\\s+[Α-ΩA-Z\u2019'ʼ\u1fbd\u0384]+\\s*\\d+(?:[/,.]\\s*\\d+(?:[./]\\d+)*)?"));
        patterns.put("legal_ref_pol", orderedSpec("body", "ΠΟΛ\\.?\\s*\\d{4}(?:[-/]\\d{2,4}[-/]\\d{2,4})?"));
        patterns.put("legal_ref_ste", orderedSpec("body", "ΣτΕ\\s*\\d+/\\d{2,4}"));
        patterns.put("legal_ref_nsk", orderedSpec("body", "ΝΣΚ\\s*\\d+/\\d{2,4}"));
        patterns.put("legal_ref_aade", orderedSpec("body", "Α\\.Α\\.Δ\\.Ε\\.|\\bΑ[ΑA]ΔΕ\\b|Δ\\.Ε\\.Δ\\.|\\bΔΕΔ\\b|Κ\\.Ε\\.ΜΕ\\.Φ\\.|Κ\\.Ε\\.ΦΟ\\.ΜΕ\\.Π\\.|Υ\\.Ε\\.Δ\\.Δ\\.Ε\\."));
        patterns.put("percentage", orderedSpec("body", "\\b\\d+(?:[.,]\\d+)?\\s*%"));
        patterns.put("fiscal_period", orderedSpec("body", "\\b\\d{2}[-/.]\\d{2}[-/.]\\d{4}\\s+έως\\s+\\d{2}[-/.]\\d{2}[-/.]\\d{4}|\\bφορολογική\\s+περίοδος\\s+\\d{4}"));
        DEFAULT_PATTERNS = java.util.Collections.unmodifiableMap(patterns);
    }

    static final String GREEK_CAPITALIZED = "[Α-ΩΆΈΉΊΌΎΏΪΫ][Α-Ωα-ωΆ-ώϊϋΐΰ]+";

    /** Medical terms. A set in Python (hash-seed ordered); sorted by code point here so output order is stable. */
    static final List<String> MEDICAL_TERMS = List.of(
            "ασθένεια",
            "διάγνωση",
            "διαβήτης",
            "θεραπεία",
            "καρκίνος",
            "νόσος",
            "φαρμακευτική",
            "χειρουργείο");

    static final String COMPANY_WORD = "[Α-ΩΆΈΉΊΌΎΏΪΫA-Z][Α-Ωα-ωΆ-ώa-zA-Z.&\\-]*";

    static final PyPattern APPELLANT_NAME_RE =
            PyRegex.compile("(?i:(?:ενδικοφανή\\s+προσφυγή|προσφυγή)\\s+τ(?:ης|ου))\\s+((?:[Α-ΩΆΈΉΊΌΎΏΪΫ][Α-Ωα-ωΆ-ώϊϋΐΰ]+)(?:\\s+(?:[Α-ΩΆΈΉΊΌΎΏΪΫ][Α-Ωα-ωΆ-ώϊϋΐΰ]+))*)", 0);

    static final PyPattern AUTHORITY_HEADER_CUES =
            PyRegex.compile("ΕΛΛΗΝΙΚΗ\\s+ΔΗΜΟΚΡΑΤΙΑ|ΔΙΕΥΘΥΝΣΗ\\s+ΕΠΙΛΥΣΗΣ\\s+ΔΙΑΦΟΡΩΝ|ΥΠΟΔΙΕΥΘΥΝΣΗ\\s+ΕΠΑΝΕΞΕΤΑΣΗΣ|Α\\.Α\\.Δ\\.Ε\\.|Α[ΑA]ΔΕ|Ταχ\\.\\s*Δ/νση|Ταχ\\.\\s*Κώδικας|Τηλέφωνο|Fax|E-mail", PyRegex.IGNORECASE);

    static final PyPattern BANK_ACCOUNT_RE =
            PyRegex.compile("(?i:λογ\\.\\s*|λογαριασμ[οό]ν?\\s*)([A-ZΑ-Ω]{2}[0-9A-ZΑ-Ω\\s]{4,29}[0-9A-ZΑ-Ω]|[0-9]{6,26})", 0);

    static final PyPattern BENEFICIARY_RE =
            PyRegex.compile("(?i:δικαιούχ[οη]\\s+τ(?:ον|ην))\\s+([Α-ΩΆΈΉΊΌΎΏΪΫ][Α-Ωα-ωΆ-ώϊϋΐΰ]+(?:\\s+[Α-ΩΆΈΉΊΌΎΏΪΫ][Α-Ωα-ωΆ-ώϊϋΐΰ]+)*)", 0);

    static final PyPattern BUSINESS_SEAT_RE =
            PyRegex.compile("με\\s+έδρα\\s+(?:τ(?:ην|ον)\\s+)?([Α-ΩΆΈΉΊΌΎΏΪΫ][Α-Ωα-ωΆ-ώ,.\\s\\d]+?)(?=\\s{2,}|\\.|,\\s*(?:οδός|αρ\\.|\\d)|\\n|$)", PyRegex.IGNORECASE);

    static final PyPattern CHALLENGED_ACT_CONTEXT_RE =
            PyRegex.compile("Οριστικ|Πράξ[ηή]|Διορθωτικ|Φ\\.Π\\.Α|Τελών|φόρου|προστίμου|Επιβολής", PyRegex.IGNORECASE);

    static final PyPattern CHALLENGED_ACT_RE =
            PyRegex.compile("(?:υπ[\u2019'ʼ\u1fbd\u0384]\\s*αρ(?:ιθ)?\\.?|με\\s+αριθ\\.?)\\s+([0-9Α-ΩA-Z][0-9Α-ΩA-Z./\\-]+)", PyRegex.IGNORECASE);

    static final PyPattern COMPANY_NAME_AFTER_CTX =
            PyRegex.compile("(?i:με\\s+επωνυμία\\s+|εταιρε?ία\\s+|εκδότρια\\s+(?:νομική\\s+οντότητα\\s+)?)([Α-ΩΆΈΉΊΌΎΏΪΫA-Z][Α-Ωα-ωΆ-ώa-zA-Z.&\\-]*(?:\\s+(?:&\\s+)?[Α-ΩΆΈΉΊΌΎΏΪΫA-Z][Α-Ωα-ωΆ-ώa-zA-Z.&\\-]*)*(?:\\s+(?:Α\\.?Ε\\.?|Ε\\.?Π\\.?Ε\\.?|Ι\\.?Κ\\.?Ε\\.?|Ο\\.?Ε\\.?|Ε\\.?Ε\\.?))?)", 0);

    static final PyPattern DATE_SUFFIX_RE =
            PyRegex.compile("^(.*?)([/\\-])(\\d{2}[/\\-.]\\d{2}[/\\-.]\\d{4})$", 0);

    static final PyPattern DECISION_NUMBER_RE =
            PyRegex.compile("Αριθμ[οό]ς\\s+[Αα]πόφασης\\s*:\\s*\\d+", PyRegex.IGNORECASE);

    static final PyPattern DECISION_PLACE_DATE_RE =
            PyRegex.compile("(?:Αθήνα|Καλλιθέα|Θεσσαλονίκη|Πάτρα|Ηράκλειο|Λάρισα|Βόλος|Ιωάννινα)[,\\s]+\\d{2}[-/.]\\d{2}[-/.]\\d{4}", PyRegex.IGNORECASE);

    static final PyPattern DECISION_TITLE_RE =
            PyRegex.compile("ΑΠΟΦΑΣΗ\\b", 0);

    static final PyPattern FATHER_NAME_RE =
            PyRegex.compile("\\b(?i:τ(?:ου|ης))\\s+([Α-ΩΆΈΉΊΌΎΏΪΫ][Α-Ωα-ωΆ-ώϊϋΐΰ]+(?:\\s+[Α-ΩΆΈΉΊΌΎΏΪΫ][Α-Ωα-ωΆ-ώϊϋΐΰ]+)*)\\s+(?i:με\\s+ΑΦΜ|κάτοικ|οδός|ατομική)", 0);

    static final PyPattern FISCAL_ID_RE =
            PyRegex.compile("(?:αριθμ[οό]\\s+μητρώου|ταμειακ[ήη]\\s+(?:μηχαν[ήη]\\s+)?|ΦΗΜ\\s+)([A-ZΑ-Ω0-9*]{2,}[\\s\\-]*[A-ZΑ-Ω0-9*]{2,})", PyRegex.IGNORECASE);

    static final PyPattern INVOICE_CELL_RE =
            PyRegex.compile("\\b(?:ΤΙΜ\\.?|ΤΠΥ|ΔΑ|ΑΠΥ|ΤΔΑ|ΔΕΛΤΙΟ)\\s*[0-9Α-ΩA-Z./-]+(?:\\s*σειρά\\s*[Α-ΩA-Z])?", 0);

    static final PyPattern INVOICE_PARAGRAPH_RE =
            PyRegex.compile("\\b(?:ΤΙΜ\\.?|ΤΠΥ|ΔΑ|ΑΠΥ|ΤΔΑ|ΔΕΛΤΙΟ)\\s*([0-9Α-ΩA-Z./-]+)(?:\\s*σειρά\\s*([Α-ΩA-Z]))?", 0);

    static final PyPattern ISOLATED_ALLCAPS_NAME_RE =
            PyRegex.compile("^[Α-ΩΆΈΉΊΌΎΏΪΫ]+(?:\\s+[Α-ΩΆΈΉΊΌΎΏΪΫ]+){1,3}$", 0);

    static final PyPattern PARTIAL_STAR_RE =
            PyRegex.compile("\\b[A-ZΑ-Ω]{2,}\\s*\\*+[0-9A-ZΑ-Ω]+\\b", 0);

    static final PyPattern PRIVATE_ADDRESS_RE =
            PyRegex.compile("(?:κάτοικ(?:ος|η)\\s+|οδός\\s+)([Α-ΩΆΈΉΊΌΎΏΪΫ][Α-Ωα-ωΆ-ώϊϋΐΰ\\s,.\\d]+?)(?=\\s{2,}|\\.|,\\s*[Ττ][Κκ]|\\n|$)", PyRegex.IGNORECASE);

    static final PyPattern PRIVATE_PARTY_CUE_RE =
            PyRegex.compile("προσφεύγ|υπόχρε|ΑΦΜ|κάτοικ|έδρα|δικαιούχ|πατέρ|αδελφ|σύζυγ|λογαριασμ", PyRegex.IGNORECASE);

    static final PyPattern SIGNATURE_TITLE_RE =
            PyRegex.compile("Ακριβ[εέ]ς\\s+[Αα]ντίγραφο|ΜΕ\\s+ΕΝΤΟΛΗ|Με\\s+εντολή|Ο\\s+ΠΡΟΪΣΤΑΜΕΝΟΣ|Η\\s+ΠΡΟΪΣΤΑΜΕΝΗ|Ο\\s+ΔΙΕΥΘΥΝΤΗΣ|Η\\s+ΔΙΕΥΘΥΝΤΡΙΑ|Υποδιεύθυνσης\\s+Επανεξέτασης|Διοικητικής\\s+Υποστήριξης", PyRegex.IGNORECASE);

    private DetectorPatterns() {
    }

    private static Map<String, String> orderedSpec(String... keyValues) {
        Map<String, String> spec = new LinkedHashMap<>();
        for (int i = 0; i < keyValues.length; i += 2) {
            spec.put(keyValues[i], keyValues[i + 1]);
        }
        return java.util.Collections.unmodifiableMap(spec);
    }
}
