// GENERATED by tools/gen_constants.py from anonymizer/postcheck_support.py (constants) — do not edit by hand; regenerate.
package dev.filtsiap.ded.anonymizer;

import dev.filtsiap.ded.anonymizer.pycompat.PyRegex;
import dev.filtsiap.ded.anonymizer.pycompat.PyRegex.PyPattern;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

/** Regex and data constants of the post-redaction audit (port of {@code postcheck_support.py}). */
final class PostcheckPatterns {

    /** {@code qa_patterns}, insertion-ordered. */
    static final Map<String, PyPattern> QA_PATTERNS;

    static {
        Map<String, PyPattern> qa = new LinkedHashMap<>();
        qa.put("AFM", PyRegex.compile("\\b(\\d{9})\\b", 0));
        qa.put("AMKA", PyRegex.compile("\\b((0[1-9]|[12]\\d|3[01])(0[1-9]|1[0-2])\\d{2}\\d{5})\\b", 0));
        qa.put("IBAN_GR", PyRegex.compile("\\bGR\\d{2}\\d{7}\\d{16}\\b", PyRegex.IGNORECASE));
        qa.put("EMAIL", PyRegex.compile("[a-zA-Z0-9._%+\\-]+@[a-zA-Z0-9.\\-]+\\.[a-zA-Z]{2,}", 0));
        qa.put("PHONE", PyRegex.compile("(?<!\\d)(?:\\+?30|0030)?[\\s\\-]?(?:69|2\\d)[\\d\\s\\-]{8,14}(?!\\d)", 0));
        qa.put("DIGIT_RUN", PyRegex.compile("\\b\\d{9,11}\\b", 0));
        QA_PATTERNS = java.util.Collections.unmodifiableMap(qa);
    }

    static final PyPattern BENEFICIARY_LEAK_RE =
            PyRegex.compile("δικαιούχ[οη]\\s+τ(?:ον|ην)\\s+[Α-ΩΆ-Ώ][α-ωά-ώ]+", PyRegex.IGNORECASE);

    static final PyPattern CASE_REF_LEAK_RE =
            PyRegex.compile("(?:υπ['\u2019]\\s*αρ(?:ιθ)?\\.?|αρ\\.?\\s*πρωτ\\.?|αριθμ[οό]\\s+πρωτοκόλλου|εντολ[ήέ]ς?\\s+(?:μερικού\\s+)?ελέγχου|Γνωστοποίησ[ηεις]+|Αίτημ[αα]\\s+Παροχής\\s+Πληροφοριών|ΑΒΜ|ΕΞ)\\s+(\\d[0-9A-ZΑ-Ω./\\-]{2,})", PyRegex.IGNORECASE);

    static final PyPattern DECISION_BODY_START_RE =
            PyRegex.compile("\\bΑΠΟΦΑΣΗ\\b", PyRegex.IGNORECASE);

    static final PyPattern ELLIPSIS_RUN_RE =
            PyRegex.compile("\u2026+", 0);

    static final PyPattern OFFICIAL_CONTACT_LABEL_RE =
            PyRegex.compile("Τηλέφωνο|Τηλ\\.?|τηλ\\.?|Fax|Φαξ|Ταχ\\.", PyRegex.IGNORECASE);

    static final PyPattern OFFICIAL_HEADER_CONTEXT_RE =
            PyRegex.compile("ΕΛΛΗΝΙΚΗ\\s+ΔΗΜΟΚΡΑΤΙΑ|Α\\.?\\s*Α\\.?\\s*Δ\\.?\\s*Ε\\.?|ΑΑΔΕ|Δ\\.?\\s*Ε\\.?\\s*Δ\\.?|ΔΕΔ|ΔΙΕΥΘΥΝΣΗ\\s+ΕΠΙΛΥΣΗΣ\\s+ΔΙΑΦΟΡΩΝ|ΥΠΟΔΙΕΥΘΥΝΣΗ\\s+ΕΠΑΝΕΞΕΤΑΣΗΣ", PyRegex.IGNORECASE);

    static final PyPattern OVER_REDACT_RE =
            PyRegex.compile("Αριθμ[οό]ς\\s+[Αα]πόφασης\\s*:\\s*\\.{3,}|ν\\.\\s*\\.{3,}|ΦΕΚ\\s+\\.{3,}|ΠΟΛ\\s*\\.{3,}|ΣτΕ\\s*\\.{3,}|ΝΣΚ\\s*\\.{3,}|\\.{2,}%", PyRegex.IGNORECASE);

    static final PyPattern PARTIAL_STAR_RESIDUE_RE =
            PyRegex.compile("\\b[A-ZΑ-Ω]{2,}\\s*\\*+[0-9A-ZΑ-Ω]+\\b", 0);

    static final PyPattern PERSON_LEAK_RE =
            PyRegex.compile("(?:ενδικοφανή\\s+προσφυγή\\s+τ(?:ης|ου)\\s+|με\\s+ΑΦΜ\\s+\\.+\\s+)([Α-ΩΆΈΉΊΌΎΏΪΫ][Α-Ωα-ωΆ-ώ]+(?:\\s+[Α-ΩΆΈΉΊΌΎΏΪΫ][Α-Ωα-ωΆ-ώ]+)+)", PyRegex.IGNORECASE);

    static final PyPattern WRONG_PLACEHOLDER_RE =
            PyRegex.compile("\\[(?:NAME|AFM|ADDRESS|COMPANY|ACT_NUMBER|REDACTED)\\]|<REDACTED>|(?:PERSON|COMPANY)_\\d+|\\*{3,}\\d+|\\*{5,}", PyRegex.IGNORECASE);

    /** Normalized invoice column headers (membership only). */
    static final Set<String> INVOICE_COLUMN_HEADERS = Set.of(
            "αρ. παραστατικου",
            "αριθμοσ",
            "παρα στατικο",
            "παραστατικο",
            "στοιχειο",
            "τιμ.",
            "τιμολογιο");

    private PostcheckPatterns() {
    }
}
