"""Dev tool: emits Java constants from the live Python modules so regexes and prompt text
are transcribed mechanically, never by hand. Run from the repo root with the Python
package importable:  PYTHONPATH=<python-repo> python3 tools/gen_constants.py
Regenerate whenever anonymizer/detector_patterns.py, postcheck_support.py or
llm/prompts.py change. Output files are ordinary source; commit them."""
import re, sys, unicodedata
from pathlib import Path

import anonymizer.detector_patterns as dp
import anonymizer.postcheck_support as ps
import anonymizer.llm.prompts as pr

OUT = Path(__file__).resolve().parent.parent / "src/main/java/dev/filtsiap/ded/anonymizer"

def lit(s: str) -> str:
    out = []
    for ch in s:
        o = ord(ch)
        if ch == "\\": out.append("\\\\")
        elif ch == '"': out.append('\\"')
        elif ch == "\n": out.append("\\n")
        elif ch == "\t": out.append("\\t")
        elif ch == "\r": out.append("\\r")
        elif o < 0x20 or o == 0x7f: out.append("\\u%04x" % o)
        elif o < 0x80: out.append(ch)
        elif unicodedata.category(ch)[0] in "LN" or ch == "€": out.append(ch)
        elif o > 0xffff: out.append("".join("\\u%04x" % u for u in ch.encode("utf-16-be").hex_units()) if False else "".join("\\u%04x" % c for c in (0xd800 + ((o - 0x10000) >> 10), 0xdc00 + ((o - 0x10000) & 0x3ff))))
        else: out.append("\\u%04x" % o)
    return '"' + "".join(out) + '"'

def flags(p):
    f = []
    if p.flags & re.IGNORECASE: f.append("PyRegex.IGNORECASE")
    if p.flags & re.DOTALL: f.append("PyRegex.DOTALL")
    return " | ".join(f) or "0"

def jname(n): return n.lstrip("_")

def pattern_const(name, p, indent="    "):
    return f"{indent}static final PyPattern {jname(name)} =\n{indent}        PyRegex.compile({lit(p.pattern)}, {flags(p)});\n"

HEADER = "// GENERATED by tools/gen_constants.py from {src} — do not edit by hand; regenerate.\n"

# ----------------------------------------------------------------- DetectorPatterns
lines = [HEADER.format(src="anonymizer/detector_patterns.py"),
         "package dev.filtsiap.ded.anonymizer;\n\n",
         "import dev.filtsiap.ded.anonymizer.pycompat.PyRegex;\n",
         "import dev.filtsiap.ded.anonymizer.pycompat.PyRegex.PyPattern;\n",
         "import java.util.LinkedHashMap;\nimport java.util.List;\nimport java.util.Map;\n\n",
         "/** Regex and data constants for the deterministic detectors (port of {@code detector_patterns.py}). */\n",
         "final class DetectorPatterns {\n\n",
         "    /** Apostrophe variants used for the Greek elision in \"υπ' αριθ.\" and FEK series letters. */\n",
         f"    static final String ELISION_APOSTROPHES = {lit(dp._ELISION_APOSTROPHES)};\n\n",
         "    /** Built-in pattern specs by name; {@code config/regex_patterns.yaml} overrides per key. Insertion-ordered. */\n",
         "    static final Map<String, Map<String, String>> DEFAULT_PATTERNS;\n\n",
         "    static {\n        Map<String, Map<String, String>> patterns = new LinkedHashMap<>();\n"]
for name, spec in dp._DEFAULT_PATTERNS.items():
    items = ", ".join(f"{lit(k)}, {lit(v)}" for k, v in spec.items())
    lines.append(f"        patterns.put({lit(name)}, orderedSpec({items}));\n")
lines.append("        DEFAULT_PATTERNS = java.util.Collections.unmodifiableMap(patterns);\n    }\n\n")
lines.append(f"    static final String GREEK_CAPITALIZED = {lit(dp._GREEK_CAPITALIZED)};\n\n")
lines.append("    /** Medical terms. A set in Python (hash-seed ordered); sorted by code point here so output order is stable. */\n")
lines.append("    static final List<String> MEDICAL_TERMS = List.of(\n" +
             ",\n".join("            " + lit(t) for t in sorted(dp._MEDICAL_TERMS)) + ");\n\n")
lines.append(f"    static final String COMPANY_WORD = {lit(dp._COMPANY_WORD)};\n\n")
for name in dir(dp):
    obj = getattr(dp, name)
    if isinstance(obj, re.Pattern):
        lines.append(pattern_const(name, obj) + "\n")
lines.append("""    private DetectorPatterns() {
    }

    private static Map<String, String> orderedSpec(String... keyValues) {
        Map<String, String> spec = new LinkedHashMap<>();
        for (int i = 0; i < keyValues.length; i += 2) {
            spec.put(keyValues[i], keyValues[i + 1]);
        }
        return java.util.Collections.unmodifiableMap(spec);
    }
}
""")
(OUT / "DetectorPatterns.java").write_text("".join(lines), encoding="utf-8")

# ----------------------------------------------------------------- PostcheckSupport patterns
lines = [HEADER.format(src="anonymizer/postcheck_support.py (constants)"),
         "package dev.filtsiap.ded.anonymizer;\n\n",
         "import dev.filtsiap.ded.anonymizer.pycompat.PyRegex;\n",
         "import dev.filtsiap.ded.anonymizer.pycompat.PyRegex.PyPattern;\n",
         "import java.util.LinkedHashMap;\nimport java.util.Map;\nimport java.util.Set;\n\n",
         "/** Regex and data constants of the post-redaction audit (port of {@code postcheck_support.py}). */\n",
         "final class PostcheckPatterns {\n\n",
         "    /** {@code qa_patterns}, insertion-ordered. */\n",
         "    static final Map<String, PyPattern> QA_PATTERNS;\n\n    static {\n        Map<String, PyPattern> qa = new LinkedHashMap<>();\n"]
for k, p in ps.qa_patterns.items():
    lines.append(f"        qa.put({lit(k)}, PyRegex.compile({lit(p.pattern)}, {flags(p)}));\n")
lines.append("        QA_PATTERNS = java.util.Collections.unmodifiableMap(qa);\n    }\n\n")
for name in dir(ps):
    obj = getattr(ps, name)
    if isinstance(obj, re.Pattern):
        lines.append(pattern_const(name, obj) + "\n")
lines.append("    /** Normalized invoice column headers (membership only). */\n")
lines.append("    static final Set<String> INVOICE_COLUMN_HEADERS = Set.of(\n" +
             ",\n".join("            " + lit(h) for h in sorted(ps._INVOICE_COLUMN_HEADERS)) + ");\n\n")
lines.append("    private PostcheckPatterns() {\n    }\n}\n")
(OUT / "PostcheckPatterns.java").write_text("".join(lines), encoding="utf-8")

# ----------------------------------------------------------------- Prompts text
core = pr._PROMPT_CORE
assert pr.SYSTEM_PROMPT_PASS1.startswith(core) and pr.SYSTEM_PROMPT_PASS2.startswith(core)
def block(s, indent=" " * 12):
    # Java text block that evaluates to exactly s (no trailing newline).
    body = []
    for line in s.split("\n"):
        line = line.replace("\\", "\\\\").replace('"""', '\\"""')
        if line.endswith(" "): line = line[:-1] + "\\s"
        body.append(indent + line if line else "")
    return '"""\n' + "\n".join(body) + '"""'
lines = [HEADER.format(src="anonymizer/llm/prompts.py (system prompt text)"),
         "package dev.filtsiap.ded.anonymizer.llm;\n\n",
         "/** The two system prompts, verbatim (port of the constants in {@code llm/prompts.py}). */\n",
         "final class PromptText {\n\n",
         "    /** Shared category/decision core, so the two passes cannot drift apart on the schema. */\n",
         f"    static final String PROMPT_CORE = {block(core)};\n\n",
         f"    static final String SYSTEM_PROMPT_PASS1 = PROMPT_CORE + {block(pr.SYSTEM_PROMPT_PASS1[len(core):])};\n\n",
         f"    static final String SYSTEM_PROMPT_PASS2 = PROMPT_CORE + {block(pr.SYSTEM_PROMPT_PASS2[len(core):])};\n\n",
         f"    /** Expected {{@code PROMPTS_SHA256}}; {{@code Prompts}} asserts the computed hash equals it at class load. */\n",
         f"    static final String PYTHON_PROMPTS_SHA256 = {lit(pr.PROMPTS_SHA256)};\n\n",
         "    private PromptText() {\n    }\n}\n"]
(OUT / "llm/PromptText.java").write_text("".join(lines), encoding="utf-8")
print("generated DetectorPatterns, PostcheckPatterns, PromptText")

# ----------------------------------------------------------------- IBAN registry (python-stdnum)
import stdnum, os
dat = Path(os.path.dirname(stdnum.__file__)) / "iban.dat"
entries = []
for raw in dat.read_text(encoding="utf-8").splitlines():
    if not raw or raw.startswith("#"): continue
    cc = raw.split()[0]
    m = re.search(r'bban="([^"]*)"', raw)
    entries.append((cc, m.group(1) if m else ""))
lines = [HEADER.format(src="python-stdnum %s stdnum/iban.dat" % stdnum.__version__),
         "package dev.filtsiap.ded.anonymizer;\n\n",
         "import java.util.Map;\n\n",
         "/** BBAN structures per country, from the IBAN registry python-stdnum validates against. */\n",
         "final class IbanRegistry {\n\n",
         "    /** Country code to BBAN structure ({@code n} digits, {@code a} upper letters, {@code c} alphanumerics). */\n",
         "    static final Map<String, String> BBAN_STRUCTURE = Map.ofEntries(\n"]
lines.append(",\n".join(f"            Map.entry({lit(cc)}, {lit(b)})" for cc, b in entries) + ");\n\n")
lines.append("    private IbanRegistry() {\n    }\n}\n")
(OUT / "IbanRegistry.java").write_text("".join(lines), encoding="utf-8")
print("generated IbanRegistry (%d countries)" % len(entries))
